- name: Copying context
  copy:
    src: context.xml
    dest: /opt/tomcat/{{ tomcat_v }}/webapps/manager/META-INF/context.xml
    owner: "{{ tomcat_user }}"
    group: "{{ tomcat_group }}"
  become: true
  become_method: sudo

- name: Copying tomcat-users
  copy:
    src: tomcat.users.xml
    dest: /opt/tomcat/{{ tomcat_v }}/conf/tomcat-users.xml
    owner: "{{ tomcat_user }}"
    group: "{{ tomcat_group }}"
  become: true
  become_method: sudo

- name: restarting_tomcat
  systemd:
    name: tomcat
    state: restarted
  become: true
  become_method: sudo

- name: Deploying task 
  deploy:
    url: "mntexam"
    war: "mnt-exam.war"
    username: "admin"
    password: "admin"



