tomcat_user: tomcat_as
tomcat_group: tomcat_as_group
tomcat_v: 8.5.0
tomcat_urls:
  8.5.24: http://archive.apache.org/dist/tomcat/tomcat-{{ tomcat_v.split('.')[0] }}/v{{ tomcat_v }}/bin/apache-tomcat-{{ tomcat_v }}.tar.gz
  8.5.2: http://archive.apache.org/dist/tomcat/tomcat-{{ tomcat_v.split('.')[0] }}/v{{ tomcat_v }}/bin/apache-tomcat-{{ tomcat_v }}.tar.gz
  8.5.0: http://archive.apache.org/dist/tomcat/tomcat-{{ tomcat_v.split('.')[0] }}/v{{ tomcat_v }}/bin/apache-tomcat-{{ tomcat_v }}.tar.gz
  7.0.82: http://archive.apache.org/dist/tomcat/tomcat-{{ tomcat_v.split('.')[0] }}/v{{ tomcat_v }}/bin/apache-tomcat-{{ tomcat_v }}.tar.gz
  7.0.6: http://archive.apache.org/dist/tomcat/tomcat-{{ tomcat_v.split('.')[0] }}/v{{ tomcat_v }}/bin/apache-tomcat-{{ tomcat_v }}.tar.gz
tomcat_link: "{{ tomcat_urls[tomcat_v] }}"
catalina_home: /opt/tomcat/{{ tomcat_v }}
