- name: Installing nginx
  yum:
    name: nginx
    state: present
  become: true
  become_user: root

#- name: Copying nginx.conf
#  copy:
#    src: files/nginx.conf
#    dest: /etc/nginx/nginx.conf
#  become: true
#  become_method: sudo
# notify: Restarting nginx

- name: Copying nginx.conf file
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/nginx.conf
  become: true
  become_method: sudo
  notify: Restarting nginx

- name: Starting nginx
  systemd:
    name: nginx
    state: started
  become: true
  become_method: sudo
